server:
  port: 8080

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToke:  ${TWILIO_AUTH_TOKEN}

logging:
  level:
    root: INFO
    com:
      twilio: DEBUG